//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SriLankanParadise.ERP.UserManagement.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SriLankanParadise.ERP.UserManagement.Shared.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch created successfully.
        /// </summary>
        public static string BatchCreated {
            get {
                return ResourceManager.GetString("BatchCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batches not found.
        /// </summary>
        public static string BatchesNotFound {
            get {
                return ResourceManager.GetString("BatchesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batches retrieved.
        /// </summary>
        public static string BatchesRetrieved {
            get {
                return ResourceManager.GetString("BatchesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchHasGrnMaster created successfully.
        /// </summary>
        public static string BatchHasGrnMasterCreated {
            get {
                return ResourceManager.GetString("BatchHasGrnMasterCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business type created successfully.
        /// </summary>
        public static string BusinessTypeCreated {
            get {
                return ResourceManager.GetString("BusinessTypeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business types retrieved.
        /// </summary>
        public static string BusinessTypesRetrieved {
            get {
                return ResourceManager.GetString("BusinessTypesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier expense out created successfully.
        /// </summary>
        public static string CashierExpenseOutCreated {
            get {
                return ResourceManager.GetString("CashierExpenseOutCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier expense outs not found.
        /// </summary>
        public static string CashierExpenseOutsNotFound {
            get {
                return ResourceManager.GetString("CashierExpenseOutsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier expense outs Retrieved.
        /// </summary>
        public static string CashierExpenseOutsRetrieved {
            get {
                return ResourceManager.GetString("CashierExpenseOutsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier session created successfully.
        /// </summary>
        public static string CashierSessionCreated {
            get {
                return ResourceManager.GetString("CashierSessionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier session not found.
        /// </summary>
        public static string CashierSessionNotFound {
            get {
                return ResourceManager.GetString("CashierSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier sessions retrieved.
        /// </summary>
        public static string CashierSessionsRetrieved {
            get {
                return ResourceManager.GetString("CashierSessionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier session updated successfully.
        /// </summary>
        public static string CashierSessionUpdated {
            get {
                return ResourceManager.GetString("CashierSessionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories not found.
        /// </summary>
        public static string CategoriesNotFound {
            get {
                return ResourceManager.GetString("CategoriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories retrieved.
        /// </summary>
        public static string CategoriesRetrieved {
            get {
                return ResourceManager.GetString("CategoriesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category created successfully.
        /// </summary>
        public static string CategoryCreated {
            get {
                return ResourceManager.GetString("CategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category deleted successfully.
        /// </summary>
        public static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category updated successfully.
        /// </summary>
        public static string CategoryUpdated {
            get {
                return ResourceManager.GetString("CategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and deduction applied created successfully.
        /// </summary>
        public static string ChargesAndDeductionAppliedCreated {
            get {
                return ResourceManager.GetString("ChargesAndDeductionAppliedCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and deduction applied deleted.
        /// </summary>
        public static string ChargesAndDeductionAppliedDeleted {
            get {
                return ResourceManager.GetString("ChargesAndDeductionAppliedDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and deduction applied not found.
        /// </summary>
        public static string ChargesAndDeductionAppliedNotFound {
            get {
                return ResourceManager.GetString("ChargesAndDeductionAppliedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and deduction applied updated successfully.
        /// </summary>
        public static string ChargesAndDeductionAppliedUpdated {
            get {
                return ResourceManager.GetString("ChargesAndDeductionAppliedUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and deduction created successfully.
        /// </summary>
        public static string ChargesAndDeductionCreated {
            get {
                return ResourceManager.GetString("ChargesAndDeductionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and deductions applied not found.
        /// </summary>
        public static string ChargesAndDeductionsAppliedNotFound {
            get {
                return ResourceManager.GetString("ChargesAndDeductionsAppliedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and deductions applied retrieved.
        /// </summary>
        public static string ChargesAndDeductionsAppliedRetrieved {
            get {
                return ResourceManager.GetString("ChargesAndDeductionsAppliedRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and deductions not found.
        /// </summary>
        public static string ChargesAndDeductionsNotFound {
            get {
                return ResourceManager.GetString("ChargesAndDeductionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges and deductions retrieved.
        /// </summary>
        public static string ChargesAndDeductionsRetrieved {
            get {
                return ResourceManager.GetString("ChargesAndDeductionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies retrieved.
        /// </summary>
        public static string CompaniesRetrieved {
            get {
                return ResourceManager.GetString("CompaniesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company created successfully.
        /// </summary>
        public static string CompanyCreated {
            get {
                return ResourceManager.GetString("CompanyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company deleted successfully.
        /// </summary>
        public static string CompanyDeleted {
            get {
                return ResourceManager.GetString("CompanyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company logo uploaded successfully.
        /// </summary>
        public static string CompanyLogoUploaded {
            get {
                return ResourceManager.GetString("CompanyLogoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found.
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company retrieved.
        /// </summary>
        public static string CompanyRetrieved {
            get {
                return ResourceManager.GetString("CompanyRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module created successfully.
        /// </summary>
        public static string CompanySubscriptionModuleCreated {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module not found.
        /// </summary>
        public static string CompanySubscriptionModuleNotFound {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module retrieved.
        /// </summary>
        public static string CompanySubscriptionModuleRetrieved {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription modules retrieved.
        /// </summary>
        public static string CompanySubscriptionModulesRetrieved {
            get {
                return ResourceManager.GetString("CompanySubscriptionModulesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module updated successfully.
        /// </summary>
        public static string CompanySubscriptionModuleUpdated {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module user created successfully.
        /// </summary>
        public static string CompanySubscriptionModuleUserCreated {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company type created successfully.
        /// </summary>
        public static string CompanyTypeCreated {
            get {
                return ResourceManager.GetString("CompanyTypeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company types retrieved.
        /// </summary>
        public static string CompanyTypesRetrieved {
            get {
                return ResourceManager.GetString("CompanyTypesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company updated successfully.
        /// </summary>
        public static string CompanyUpdated {
            get {
                return ResourceManager.GetString("CompanyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer created successfully.
        /// </summary>
        public static string CustomerCreated {
            get {
                return ResourceManager.GetString("CustomerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers not found.
        /// </summary>
        public static string CustomersNotFound {
            get {
                return ResourceManager.GetString("CustomersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers retrieved.
        /// </summary>
        public static string CustomersRetrieved {
            get {
                return ResourceManager.GetString("CustomersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense out requisition created successfully.
        /// </summary>
        public static string ExpenseOutRequisitionCreated {
            get {
                return ResourceManager.GetString("ExpenseOutRequisitionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense out requisition not found.
        /// </summary>
        public static string ExpenseOutRequisitionNotFound {
            get {
                return ResourceManager.GetString("ExpenseOutRequisitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense out requisition retrieved.
        /// </summary>
        public static string ExpenseOutRequisitionRetrieved {
            get {
                return ResourceManager.GetString("ExpenseOutRequisitionRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense out requisitions not found.
        /// </summary>
        public static string ExpenseOutRequisitionsNotFound {
            get {
                return ResourceManager.GetString("ExpenseOutRequisitionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense out requisitions retrieved.
        /// </summary>
        public static string ExpenseOutRequisitionsRetrieved {
            get {
                return ResourceManager.GetString("ExpenseOutRequisitionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense out requisition updated successfully.
        /// </summary>
        public static string ExpenseOutRequisitionUpdated {
            get {
                return ResourceManager.GetString("ExpenseOutRequisitionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn detail created successfully.
        /// </summary>
        public static string GrnDetailCreated {
            get {
                return ResourceManager.GetString("GrnDetailCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn detail deleted successfully.
        /// </summary>
        public static string GrnDetailDeleted {
            get {
                return ResourceManager.GetString("GrnDetailDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn detail not found.
        /// </summary>
        public static string GrnDetailNotFound {
            get {
                return ResourceManager.GetString("GrnDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn detail updated successfully.
        /// </summary>
        public static string GrnDetailUpdated {
            get {
                return ResourceManager.GetString("GrnDetailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn master approved.
        /// </summary>
        public static string GrnMasterApproved {
            get {
                return ResourceManager.GetString("GrnMasterApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn master created successfully.
        /// </summary>
        public static string GrnMasterCreated {
            get {
                return ResourceManager.GetString("GrnMasterCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn master not found.
        /// </summary>
        public static string GrnMasterNotFound {
            get {
                return ResourceManager.GetString("GrnMasterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn master retrieved.
        /// </summary>
        public static string GrnMasterRetrieved {
            get {
                return ResourceManager.GetString("GrnMasterRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn masters not found.
        /// </summary>
        public static string GrnMastersNotFound {
            get {
                return ResourceManager.GetString("GrnMastersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn masters retrieved.
        /// </summary>
        public static string GrnMastersRetrieved {
            get {
                return ResourceManager.GetString("GrnMastersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grn master updated successfully.
        /// </summary>
        public static string GrnMasterUpdated {
            get {
                return ResourceManager.GetString("GrnMasterUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue detail created successfully.
        /// </summary>
        public static string IssueDetailCreated {
            get {
                return ResourceManager.GetString("IssueDetailCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue master approved.
        /// </summary>
        public static string IssueMasterApproved {
            get {
                return ResourceManager.GetString("IssueMasterApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue master created successfully.
        /// </summary>
        public static string IssueMasterCreated {
            get {
                return ResourceManager.GetString("IssueMasterCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue master not found.
        /// </summary>
        public static string IssueMasterNotFound {
            get {
                return ResourceManager.GetString("IssueMasterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue masters not found.
        /// </summary>
        public static string IssueMastersNotFound {
            get {
                return ResourceManager.GetString("IssueMastersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue masters retrieved.
        /// </summary>
        public static string IssueMastersRetrieved {
            get {
                return ResourceManager.GetString("IssueMastersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item batch created successfully.
        /// </summary>
        public static string ItemBatchCreated {
            get {
                return ResourceManager.GetString("ItemBatchCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item batches not found.
        /// </summary>
        public static string ItemBatchesNotFound {
            get {
                return ResourceManager.GetString("ItemBatchesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item batches retrieved.
        /// </summary>
        public static string ItemBatchesRetrieved {
            get {
                return ResourceManager.GetString("ItemBatchesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemBatchHasGrnDetail created successfully.
        /// </summary>
        public static string ItemBatchHasGrnDetailCreated {
            get {
                return ResourceManager.GetString("ItemBatchHasGrnDetailCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item batch not found.
        /// </summary>
        public static string ItemBatchNotFound {
            get {
                return ResourceManager.GetString("ItemBatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item batch updated successfully.
        /// </summary>
        public static string ItemBatchUpdated {
            get {
                return ResourceManager.GetString("ItemBatchUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item master created successfully.
        /// </summary>
        public static string ItemMasterCreated {
            get {
                return ResourceManager.GetString("ItemMasterCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item master deleted successfully.
        /// </summary>
        public static string ItemMasterDeleted {
            get {
                return ResourceManager.GetString("ItemMasterDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item master not found.
        /// </summary>
        public static string ItemMasterNotFound {
            get {
                return ResourceManager.GetString("ItemMasterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item master retrieved.
        /// </summary>
        public static string ItemMasterRetrieved {
            get {
                return ResourceManager.GetString("ItemMasterRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item masters not found.
        /// </summary>
        public static string ItemMastersNotFound {
            get {
                return ResourceManager.GetString("ItemMastersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item masters retrieved.
        /// </summary>
        public static string ItemMastersRetrieved {
            get {
                return ResourceManager.GetString("ItemMastersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item master updated successfully.
        /// </summary>
        public static string ItemMasterUpdated {
            get {
                return ResourceManager.GetString("ItemMasterUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item types not found.
        /// </summary>
        public static string ItemTypesNotFound {
            get {
                return ResourceManager.GetString("ItemTypesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item types retrieved.
        /// </summary>
        public static string ItemTypesRetrieved {
            get {
                return ResourceManager.GetString("ItemTypesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationChannelItemBatch created successfully.
        /// </summary>
        public static string LocationChannelItemBatchCreated {
            get {
                return ResourceManager.GetString("LocationChannelItemBatchCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations not found.
        /// </summary>
        public static string LocationsNotFound {
            get {
                return ResourceManager.GetString("LocationsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations retrieved.
        /// </summary>
        public static string LocationsRetrieved {
            get {
                return ResourceManager.GetString("LocationsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement type created successfully.
        /// </summary>
        public static string MeasurementTypeCreated {
            get {
                return ResourceManager.GetString("MeasurementTypeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement types not found.
        /// </summary>
        public static string MeasurementTypesNotFound {
            get {
                return ResourceManager.GetString("MeasurementTypesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement types retrieved.
        /// </summary>
        public static string MeasurementTypesRetrieved {
            get {
                return ResourceManager.GetString("MeasurementTypesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module created successfully.
        /// </summary>
        public static string ModuleCreated {
            get {
                return ResourceManager.GetString("ModuleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module not found.
        /// </summary>
        public static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module retrieved.
        /// </summary>
        public static string ModuleRetrieved {
            get {
                return ResourceManager.GetString("ModuleRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules not found.
        /// </summary>
        public static string ModulesNotFound {
            get {
                return ResourceManager.GetString("ModulesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules retrieved.
        /// </summary>
        public static string ModulesRetrieved {
            get {
                return ResourceManager.GetString("ModulesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module updated successfully.
        /// </summary>
        public static string ModuleUpdated {
            get {
                return ResourceManager.GetString("ModuleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment mode created successfully.
        /// </summary>
        public static string PaymentModeCreated {
            get {
                return ResourceManager.GetString("PaymentModeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment modes not found.
        /// </summary>
        public static string PaymentModesNotFound {
            get {
                return ResourceManager.GetString("PaymentModesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment modes retrieved.
        /// </summary>
        public static string PaymentModesRetrieved {
            get {
                return ResourceManager.GetString("PaymentModesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions not found.
        /// </summary>
        public static string PermissionsNotFound {
            get {
                return ResourceManager.GetString("PermissionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions retrieved.
        /// </summary>
        public static string PermissionsRetrieved {
            get {
                return ResourceManager.GetString("PermissionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order approved.
        /// </summary>
        public static string PurchaseOrderApproved {
            get {
                return ResourceManager.GetString("PurchaseOrderApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order created successfully.
        /// </summary>
        public static string PurchaseOrderCreated {
            get {
                return ResourceManager.GetString("PurchaseOrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order detail created successfully.
        /// </summary>
        public static string PurchaseOrderDetailCreated {
            get {
                return ResourceManager.GetString("PurchaseOrderDetailCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order detail deleted.
        /// </summary>
        public static string PurchaseOrderDetailDeleted {
            get {
                return ResourceManager.GetString("PurchaseOrderDetailDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order detail not found.
        /// </summary>
        public static string PurchaseOrderDetailNotFound {
            get {
                return ResourceManager.GetString("PurchaseOrderDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order detail updated successfully.
        /// </summary>
        public static string PurchaseOrderDetailUpdated {
            get {
                return ResourceManager.GetString("PurchaseOrderDetailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order not found.
        /// </summary>
        public static string PurchaseOrderNotFound {
            get {
                return ResourceManager.GetString("PurchaseOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order retrieved.
        /// </summary>
        public static string PurchaseOrderRetrieved {
            get {
                return ResourceManager.GetString("PurchaseOrderRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase orders not found.
        /// </summary>
        public static string PurchaseOrdersNotFound {
            get {
                return ResourceManager.GetString("PurchaseOrdersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase orders retrieved.
        /// </summary>
        public static string PurchaseOrdersRetrieved {
            get {
                return ResourceManager.GetString("PurchaseOrdersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order updated successfully.
        /// </summary>
        public static string PurchaseOrderUpdated {
            get {
                return ResourceManager.GetString("PurchaseOrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisition approved.
        /// </summary>
        public static string PurchaseRequisitionApproved {
            get {
                return ResourceManager.GetString("PurchaseRequisitionApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisition created successfully.
        /// </summary>
        public static string PurchaseRequisitionCreated {
            get {
                return ResourceManager.GetString("PurchaseRequisitionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisition detail created successfully.
        /// </summary>
        public static string PurchaseRequisitionDetailCreated {
            get {
                return ResourceManager.GetString("PurchaseRequisitionDetailCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisition detail deleted successfully.
        /// </summary>
        public static string PurchaseRequisitionDetailDeleted {
            get {
                return ResourceManager.GetString("PurchaseRequisitionDetailDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisition detail not found.
        /// </summary>
        public static string PurchaseRequisitionDetailNotFound {
            get {
                return ResourceManager.GetString("PurchaseRequisitionDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisition detail updated successfully.
        /// </summary>
        public static string PurchaseRequisitionDetailUpdated {
            get {
                return ResourceManager.GetString("PurchaseRequisitionDetailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisition not found.
        /// </summary>
        public static string PurchaseRequisitionNotFound {
            get {
                return ResourceManager.GetString("PurchaseRequisitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisition retrieved.
        /// </summary>
        public static string PurchaseRequisitionRetrieved {
            get {
                return ResourceManager.GetString("PurchaseRequisitionRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisitions not found.
        /// </summary>
        public static string PurchaseRequisitionsNotFound {
            get {
                return ResourceManager.GetString("PurchaseRequisitionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisitions retrieved.
        /// </summary>
        public static string PurchaseRequisitionsRetrieved {
            get {
                return ResourceManager.GetString("PurchaseRequisitionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase requisition updated successfully.
        /// </summary>
        public static string PurchaseRequisitionUpdated {
            get {
                return ResourceManager.GetString("PurchaseRequisitionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition detail created successfully.
        /// </summary>
        public static string RequisitionDetailCreated {
            get {
                return ResourceManager.GetString("RequisitionDetailCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition master approved.
        /// </summary>
        public static string RequisitionMasterApproved {
            get {
                return ResourceManager.GetString("RequisitionMasterApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition master created successfully.
        /// </summary>
        public static string RequisitionMasterCreated {
            get {
                return ResourceManager.GetString("RequisitionMasterCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition master not found.
        /// </summary>
        public static string RequisitionMasterNotFound {
            get {
                return ResourceManager.GetString("RequisitionMasterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition masters not found.
        /// </summary>
        public static string RequisitionMastersNotFound {
            get {
                return ResourceManager.GetString("RequisitionMastersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition masters retrieved.
        /// </summary>
        public static string RequisitionMastersRetrieved {
            get {
                return ResourceManager.GetString("RequisitionMastersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role permission created successfully.
        /// </summary>
        public static string RolePermissionCreated {
            get {
                return ResourceManager.GetString("RolePermissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles not found.
        /// </summary>
        public static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles retrieved.
        /// </summary>
        public static string RolesRetrieved {
            get {
                return ResourceManager.GetString("RolesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoice approved.
        /// </summary>
        public static string SalesInvoiceApproved {
            get {
                return ResourceManager.GetString("SalesInvoiceApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoice created successfully.
        /// </summary>
        public static string SalesInvoiceCreated {
            get {
                return ResourceManager.GetString("SalesInvoiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoice detail created successfully.
        /// </summary>
        public static string SalesInvoiceDetailCreated {
            get {
                return ResourceManager.GetString("SalesInvoiceDetailCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoice detail deleted.
        /// </summary>
        public static string SalesInvoiceDetailDeleted {
            get {
                return ResourceManager.GetString("SalesInvoiceDetailDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoice detail not found.
        /// </summary>
        public static string SalesInvoiceDetailNotFound {
            get {
                return ResourceManager.GetString("SalesInvoiceDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoice detail updated successfully.
        /// </summary>
        public static string SalesInvoiceDetailUpdated {
            get {
                return ResourceManager.GetString("SalesInvoiceDetailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoice not found.
        /// </summary>
        public static string SalesInvoiceNotFound {
            get {
                return ResourceManager.GetString("SalesInvoiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoice retrieved.
        /// </summary>
        public static string SalesInvoiceRetrieved {
            get {
                return ResourceManager.GetString("SalesInvoiceRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoices not found.
        /// </summary>
        public static string SalesInvoicesNotFound {
            get {
                return ResourceManager.GetString("SalesInvoicesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoices retrieved.
        /// </summary>
        public static string SalesInvoicesRetrieved {
            get {
                return ResourceManager.GetString("SalesInvoicesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales invoice updated successfully.
        /// </summary>
        public static string SalesInvoiceUpdated {
            get {
                return ResourceManager.GetString("SalesInvoiceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order approved.
        /// </summary>
        public static string SalesOrderApproved {
            get {
                return ResourceManager.GetString("SalesOrderApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order created successfully.
        /// </summary>
        public static string SalesOrderCreated {
            get {
                return ResourceManager.GetString("SalesOrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order detail created successfully.
        /// </summary>
        public static string SalesOrderDetailCreated {
            get {
                return ResourceManager.GetString("SalesOrderDetailCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order detail deleted.
        /// </summary>
        public static string SalesOrderDetailDeleted {
            get {
                return ResourceManager.GetString("SalesOrderDetailDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order detail not found.
        /// </summary>
        public static string SalesOrderDetailNotFound {
            get {
                return ResourceManager.GetString("SalesOrderDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order detail updated successfully.
        /// </summary>
        public static string SalesOrderDetailUpdated {
            get {
                return ResourceManager.GetString("SalesOrderDetailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order not found.
        /// </summary>
        public static string SalesOrderNotFound {
            get {
                return ResourceManager.GetString("SalesOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order retrieved.
        /// </summary>
        public static string SalesOrderRetrieved {
            get {
                return ResourceManager.GetString("SalesOrderRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales orders not found.
        /// </summary>
        public static string SalesOrdersNotFound {
            get {
                return ResourceManager.GetString("SalesOrdersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales orders retrieved.
        /// </summary>
        public static string SalesOrdersRetrieved {
            get {
                return ResourceManager.GetString("SalesOrdersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales order updated successfully.
        /// </summary>
        public static string SalesOrderUpdated {
            get {
                return ResourceManager.GetString("SalesOrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales receipt created successfully.
        /// </summary>
        public static string SalesReceiptCreated {
            get {
                return ResourceManager.GetString("SalesReceiptCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales receipt not found.
        /// </summary>
        public static string SalesReceiptNotFound {
            get {
                return ResourceManager.GetString("SalesReceiptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales receipt retrieved.
        /// </summary>
        public static string SalesReceiptRetrieved {
            get {
                return ResourceManager.GetString("SalesReceiptRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesReceiptSalesInvoice created successfully.
        /// </summary>
        public static string SalesReceiptSalesInvoiceCreated {
            get {
                return ResourceManager.GetString("SalesReceiptSalesInvoiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesReceiptSalesInvoice deleted successfully.
        /// </summary>
        public static string SalesReceiptSalesInvoiceDeleted {
            get {
                return ResourceManager.GetString("SalesReceiptSalesInvoiceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesReceiptSalesInvoice not found.
        /// </summary>
        public static string SalesReceiptSalesInvoiceNotFound {
            get {
                return ResourceManager.GetString("SalesReceiptSalesInvoiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesReceiptSalesInvoice updated successfully.
        /// </summary>
        public static string SalesReceiptSalesInvoiceUpdated {
            get {
                return ResourceManager.GetString("SalesReceiptSalesInvoiceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales receipts not found.
        /// </summary>
        public static string SalesReceiptsNotFound {
            get {
                return ResourceManager.GetString("SalesReceiptsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales receipts retrieved.
        /// </summary>
        public static string SalesReceiptsRetrieved {
            get {
                return ResourceManager.GetString("SalesReceiptsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales receipt updated successfully.
        /// </summary>
        public static string SalesReceiptUpdated {
            get {
                return ResourceManager.GetString("SalesReceiptUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub module created successfully.
        /// </summary>
        public static string SubModuleCreated {
            get {
                return ResourceManager.GetString("SubModuleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub modules not found.
        /// </summary>
        public static string SubModulesNotFound {
            get {
                return ResourceManager.GetString("SubModulesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub modules retrieved.
        /// </summary>
        public static string SubModulesRetrieved {
            get {
                return ResourceManager.GetString("SubModulesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription created successfully.
        /// </summary>
        public static string SubscriptionCreated {
            get {
                return ResourceManager.GetString("SubscriptionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription expired.
        /// </summary>
        public static string SubscriptionExpired {
            get {
                return ResourceManager.GetString("SubscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription not found.
        /// </summary>
        public static string SubscriptionNotFound {
            get {
                return ResourceManager.GetString("SubscriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription retrieved.
        /// </summary>
        public static string SubscriptionRetrieved {
            get {
                return ResourceManager.GetString("SubscriptionRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions retrieved.
        /// </summary>
        public static string SubscriptionsRetrieved {
            get {
                return ResourceManager.GetString("SubscriptionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription updated successfully.
        /// </summary>
        public static string SubscriptionUpdated {
            get {
                return ResourceManager.GetString("SubscriptionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier attachment created successfully.
        /// </summary>
        public static string SupplierAttachmentCreated {
            get {
                return ResourceManager.GetString("SupplierAttachmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier attachment deleted successfully.
        /// </summary>
        public static string SupplierAttachmentDeleted {
            get {
                return ResourceManager.GetString("SupplierAttachmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier attachment not found.
        /// </summary>
        public static string SupplierAttachmentNotFound {
            get {
                return ResourceManager.GetString("SupplierAttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier attachments not found.
        /// </summary>
        public static string SupplierAttachmentsNotFound {
            get {
                return ResourceManager.GetString("SupplierAttachmentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier attachments retrieved.
        /// </summary>
        public static string SupplierAttachmentsRetrieved {
            get {
                return ResourceManager.GetString("SupplierAttachmentsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier attachment updated successfully.
        /// </summary>
        public static string SupplierAttachmentUpdated {
            get {
                return ResourceManager.GetString("SupplierAttachmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier attachment uploaded successfully.
        /// </summary>
        public static string SupplierAttachmentUploaded {
            get {
                return ResourceManager.GetString("SupplierAttachmentUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier category created successfully.
        /// </summary>
        public static string SupplierCategoryCreated {
            get {
                return ResourceManager.GetString("SupplierCategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier category deleted successfully.
        /// </summary>
        public static string SupplierCategoryDeleted {
            get {
                return ResourceManager.GetString("SupplierCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier category not found.
        /// </summary>
        public static string SupplierCategoryNotFound {
            get {
                return ResourceManager.GetString("SupplierCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier created successfully.
        /// </summary>
        public static string SupplierCreated {
            get {
                return ResourceManager.GetString("SupplierCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier deleted  successfully.
        /// </summary>
        public static string SupplierDeleted {
            get {
                return ResourceManager.GetString("SupplierDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier logo not found.
        /// </summary>
        public static string SupplierLogoNotFound {
            get {
                return ResourceManager.GetString("SupplierLogoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier logo retrieved.
        /// </summary>
        public static string SupplierLogoRetrieved {
            get {
                return ResourceManager.GetString("SupplierLogoRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier logo uploaded successfully.
        /// </summary>
        public static string SupplierLogoUploaded {
            get {
                return ResourceManager.GetString("SupplierLogoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier not found.
        /// </summary>
        public static string SupplierNotFound {
            get {
                return ResourceManager.GetString("SupplierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers not found.
        /// </summary>
        public static string SuppliersNotFound {
            get {
                return ResourceManager.GetString("SuppliersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers retrieved.
        /// </summary>
        public static string SuppliersRetrieved {
            get {
                return ResourceManager.GetString("SuppliersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier updated successfully.
        /// </summary>
        public static string SupplierUpdated {
            get {
                return ResourceManager.GetString("SupplierUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction types not found.
        /// </summary>
        public static string TransactionTypesNotFound {
            get {
                return ResourceManager.GetString("TransactionTypesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction types retrieved .
        /// </summary>
        public static string TransactionTypesRetrieved {
            get {
                return ResourceManager.GetString("TransactionTypesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit created successfully.
        /// </summary>
        public static string UnitCreated {
            get {
                return ResourceManager.GetString("UnitCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit deleted successfully.
        /// </summary>
        public static string UnitDeleted {
            get {
                return ResourceManager.GetString("UnitDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit not found.
        /// </summary>
        public static string UnitNotFound {
            get {
                return ResourceManager.GetString("UnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units not found.
        /// </summary>
        public static string UnitsNotFound {
            get {
                return ResourceManager.GetString("UnitsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units retrieved.
        /// </summary>
        public static string UnitsRetrieved {
            get {
                return ResourceManager.GetString("UnitsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit updated successfully.
        /// </summary>
        public static string UnitUpdated {
            get {
                return ResourceManager.GetString("UnitUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authenticated successfully.
        /// </summary>
        public static string UserAuthenticated {
            get {
                return ResourceManager.GetString("UserAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role created successfully.
        /// </summary>
        public static string UseRoleCreated {
            get {
                return ResourceManager.GetString("UseRoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User permission created successfully.
        /// </summary>
        public static string UserPermissionCreated {
            get {
                return ResourceManager.GetString("UserPermissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User permissions not found.
        /// </summary>
        public static string UserPermissionsNotFound {
            get {
                return ResourceManager.GetString("UserPermissionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User permissions retrieved.
        /// </summary>
        public static string UserPermissionsRetrieved {
            get {
                return ResourceManager.GetString("UserPermissionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully.
        /// </summary>
        public static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
    }
}
