//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SriLankanParadise.ERP.UserManagement.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SriLankanParadise.ERP.UserManagement.Shared.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies retrieved.
        /// </summary>
        public static string CompaniesRetrieved {
            get {
                return ResourceManager.GetString("CompaniesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company created successfully.
        /// </summary>
        public static string CompanyCreated {
            get {
                return ResourceManager.GetString("CompanyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company deleted successfully.
        /// </summary>
        public static string CompanyDeleted {
            get {
                return ResourceManager.GetString("CompanyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company logo uploaded successfully.
        /// </summary>
        public static string CompanyLogoUploaded {
            get {
                return ResourceManager.GetString("CompanyLogoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found.
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company retrieved.
        /// </summary>
        public static string CompanyRetrieved {
            get {
                return ResourceManager.GetString("CompanyRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module created successfully.
        /// </summary>
        public static string CompanySubscriptionModuleCreated {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module not found.
        /// </summary>
        public static string CompanySubscriptionModuleNotFound {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module retrieved.
        /// </summary>
        public static string CompanySubscriptionModuleRetrieved {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription modules retrieved.
        /// </summary>
        public static string CompanySubscriptionModulesRetrieved {
            get {
                return ResourceManager.GetString("CompanySubscriptionModulesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module updated successfully.
        /// </summary>
        public static string CompanySubscriptionModuleUpdated {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company subscription module user created successfully.
        /// </summary>
        public static string CompanySubscriptionModuleUserCreated {
            get {
                return ResourceManager.GetString("CompanySubscriptionModuleUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company updated successfully.
        /// </summary>
        public static string CompanyUpdated {
            get {
                return ResourceManager.GetString("CompanyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module created successfully.
        /// </summary>
        public static string ModuleCreated {
            get {
                return ResourceManager.GetString("ModuleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module not found.
        /// </summary>
        public static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module retrieved.
        /// </summary>
        public static string ModuleRetrieved {
            get {
                return ResourceManager.GetString("ModuleRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules not found.
        /// </summary>
        public static string ModulesNotFound {
            get {
                return ResourceManager.GetString("ModulesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules retrieved.
        /// </summary>
        public static string ModulesRetrieved {
            get {
                return ResourceManager.GetString("ModulesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module updated successfully.
        /// </summary>
        public static string ModuleUpdated {
            get {
                return ResourceManager.GetString("ModuleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Not Found.
        /// </summary>
        public static string PermissionsNotFound {
            get {
                return ResourceManager.GetString("PermissionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Retrieved.
        /// </summary>
        public static string PermissionsRetrieved {
            get {
                return ResourceManager.GetString("PermissionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permission created successfully.
        /// </summary>
        public static string RolePermissionCreated {
            get {
                return ResourceManager.GetString("RolePermissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Not Found.
        /// </summary>
        public static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Retrieved.
        /// </summary>
        public static string RolesRetrieved {
            get {
                return ResourceManager.GetString("RolesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Module created successfully.
        /// </summary>
        public static string SubModuleCreated {
            get {
                return ResourceManager.GetString("SubModuleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Modules not found.
        /// </summary>
        public static string SubModulesNotFound {
            get {
                return ResourceManager.GetString("SubModulesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Modules retrieved.
        /// </summary>
        public static string SubModulesRetrieved {
            get {
                return ResourceManager.GetString("SubModulesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription created successfully.
        /// </summary>
        public static string SubscriptionCreated {
            get {
                return ResourceManager.GetString("SubscriptionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription expired.
        /// </summary>
        public static string SubscriptionExpired {
            get {
                return ResourceManager.GetString("SubscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription not found.
        /// </summary>
        public static string SubscriptionNotFound {
            get {
                return ResourceManager.GetString("SubscriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription retrieved.
        /// </summary>
        public static string SubscriptionRetrieved {
            get {
                return ResourceManager.GetString("SubscriptionRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions retrieved.
        /// </summary>
        public static string SubscriptionsRetrieved {
            get {
                return ResourceManager.GetString("SubscriptionsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription updated successfully.
        /// </summary>
        public static string SubscriptionUpdated {
            get {
                return ResourceManager.GetString("SubscriptionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authenticated successfully.
        /// </summary>
        public static string UserAuthenticated {
            get {
                return ResourceManager.GetString("UserAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role created successfully.
        /// </summary>
        public static string UseRoleCreated {
            get {
                return ResourceManager.GetString("UseRoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permission created successfully.
        /// </summary>
        public static string UserPermissionCreated {
            get {
                return ResourceManager.GetString("UserPermissionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully.
        /// </summary>
        public static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
    }
}
